name: Build

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            arch: x86_64
          # - os: macos-14
          #   arch: arm64
          # - os: macos-latest
          #   arch: x86_64
          # - os: windows-latest
          #   arch: AMD64



    steps:
      - uses: actions/checkout@v4
    
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/tests"
        
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
