name: Build Package

on: [push]

jobs:
  Build-Package-Linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Setup SCIPOptSuite
        uses: ./.github/actions/setup-scipoptsuite-action

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Prepare Python Environment
        run: |
          pip install -r requirements.txt

      - name: Setup PySCIPOpt
        uses: ./.github/actions/setup-pyscipopt-action
        with:
          ref: scip-8
      
      - name: Build & Install PyGCGOpt
        run: |
          python install .
