name: Release Package TestPyPI

on:
  workflow_dispatch:

jobs:
  release-test:
    uses: scipopt/PyGCGOpt/.github/workflows/release.yml@master
    with:
      production: false
    secrets:
      PYPI_API_TOKEN: ${{ secrets.TESTPYPI_API_TOKEN }}
