name: Release Package PyPI

on:
  workflow_dispatch:

jobs:
  release-test:
    uses: scipopt/PyGCGOpt/.github/workflows/release.yml@b726a0019e1fb2c27765266adb4d700130e35679
    with:
      production: true
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
