name: Release Package to Test Environment

on:
  workflow_dispatch:

jobs:
  release-test:
    uses: scipopt/PyGCGOpt/.github/workflows/release.yml@93160a4f97a8fe0e9497fb4298795749046ae527
    with:
      production: false
    secrets:
      PYPI_API_TOKEN: ${{ secrets.TESTPYPI_API_TOKEN }}
