name: Setup PySCIPOpt

on:
  workflow_dispatch:

jobs:
  Setup-PySCIPOpt:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout PySCIPOpt
        uses: actions/checkout@v2
        with:
          repository: scipopt/PySCIPOpt.git
          ref: scip-8
          path: PySCIPOpt
      - run: echo "PySCIPOpt_HASH=$(cd PySCIPOpt && git rev-parse HEAD)" >> $GITHUB_ENV
      
      - name: Cache PySCIPOpt Build
        uses: actions/cache@v2
        with:
          path: ~/PySCIPOpt_dist
          key: ${{ runner.os }}-PySCIPOpt-${{ env.PySCIPOpt_HASH }}
      
      - name: Build & Install PySCIPOpt
        run: |
          [ ! -f ~/PySCIPOpt_dist/*.whl ] && pip install wheel && python -m build --no-isolation --wheel --outdir ~/PySCIPOpt_dist/ PySCIPOpt/
          pip install ~/PySCIPOpt_dist/*.whl
